version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud

volumes:
  postgres_data: